services:
  - type: web
    name: zeycake-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./database.sqlite
      - key: JWT_SECRET
        value: Clesecretezeycake
